version: "3.9"

services:
  # frontend:
  #   build: ./frontend
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - "5173:5173"
  # depends_on:
  #   - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=mongodb://db:27017/nestjs_app

  # nextjs:
  #   build: ./nextjs
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./nextjs:/app
  #   depends_on:
  #     - backend
